import type { Metadata } from "next";
import Header from "./components/Header";
import "./globals.css";
import { ClerkProvider,ClerkLoaded,ClerkLoading } from "@clerk/nextjs";
import Loader from "./components/Loader";

export const metadata: Metadata = {
  title: "Auth Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`antialiased`}>
        <ClerkLoading>
          <div className="fixed top-0 left-0 w-screen h-screen bg-white flex justify-center items-center">
            <Loader></Loader>
          </div>
        </ClerkLoading>
        <ClerkLoaded>
        <Header/>
        {children}
        </ClerkLoaded>
        </body>
    </html>
    </ClerkProvider>
  );
}
